A/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('account/', include('account.urls', namespace='account')),
]

account/urls.py
from django.urls import path
from . import views


app_name = 'account'
urlpatterns = [
	path('register/', views.UserRegisterView.as_view(), name='user_register'),
	path('login/', views.UserLoginView.as_view(), name='user_login'),
	path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
	path('profile/<int:user_id>/', views.UserProfileView.as_view(), name='user_profile'),
    path('reset/', views.UserPasswordResetView.as_view(), name='reset_password'),
	path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
	path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
	path('confirm/complete', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('follow/<int:user_id>', views.UserFollowView.as_view(), name='user_follow'),
	path('unfollow/<int:user_id>', views.UserUnfollowView.as_view(), name='user_unfollow'),
    path('edit_user/', views.EditUserView.as_view(), name='edit_user'),
]

home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
	path('', views.HomeView.as_view(), name='home'),
    path('page/<int:page>', views.HomeView.as_view(), name="home"),
	path('post/<int:post_id>/<slug:post_slug>/', views.PostDetailView.as_view(), name='post_detail'),
	path('post/delete/<int:post_id>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('post/update/<int:post_id>/', views.PostUpdateView.as_view(), name='post-update'),
    path('post/create/', views.PostCreateView.as_view(), name='post_create'),
    path('reply/<int:post_id>/<int:comment_id>/', views.PostAddReplyView.as_view(), name="add_reply"),
    path('like/<int:post_id>/', views.PostLikeView.as_view(), name='post_like'),
    path('search/page/<int:page>/', views.PostSearchView.as_view(), name="post_search"),
    path('search/', views.PostSearchView.as_view(), name="post_search"),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor.fields import RichTextField


class Post(models.Model):
	"""This model is for showing user posts."""

	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
	title = models.CharField(max_length=100, null=True, blank=True)
	body = RichTextField(config_name='myconfig')
	slug = models.SlugField()
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	class Meta:
		ordering=['-created']

	def __str__(self):
		return f'{self.slug} - {self.updated}'
	
	def get_absolute_url(self):
		return reverse('home:post_detail', args=(self.id, self.slug))
	
	def likes_count(self):
		"""This method is for counting the number of likes of users' posts."""
		return self.pvotes.count()
	
	def user_can_like(self, user):
		"""
        The purpose of this method is to disable the 
        like button when a user likes another user's post.
        """

		user_like = user.uvotes.filter(post=self)
		if user_like.exists():
			return True
		return False




class Comment(models.Model):
	"""This model is for put comments on posts."""

	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ucomments')
	post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pcomments')
	reply = models.ForeignKey('self', on_delete=models.CASCADE, related_name='rcomments', blank=True, null=True)
	is_reply = models.BooleanField(default=False)
	body = models.TextField(max_length=400)
	created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f'{self.user} - {self.body[:20]}'



class Vote(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='uvotes')
	post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pvotes')
	
	def __str__(self):
		return f'{self.user} likes {self.post.title}'

home/forms.py
from django import forms
from .models import Post, Comment


class PostCreateUpdateForm(forms.ModelForm):
    """This form is for creating or updating posts."""
    class Meta:
        model = Post
        fields = ('title', 'body')



class CommentCreateForm(forms.ModelForm):
    """This form is for creating post comments."""
    class Meta:
        model = Comment
        fields =('body',)
        widgets = {
            'body':forms.Textarea(attrs={'class':'form-control', 'placeholder':'Put your comment...'})
        }


class CommentReplyForm(forms.ModelForm):
    """This form is for replying to post comments."""
    class Meta:
        model= Comment
        fields = ('body',)
        widgets = {
            'body': forms.Textarea(attrs={'class':'form-control', 'placeholder':'Put your Reply...'})
        }

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.text import slugify
from django.contrib import messages
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.db.models import Q
from .models import Post, Comment, Vote
from .forms import PostCreateUpdateForm, CommentCreateForm, CommentReplyForm

class HomeView(ListView):
	"""This view is related to our main page and pagination."""
	queryset = Post.objects.all()
	paginate_by = 4



class PostDetailView(View):
	"""
	This view is related to our detail page, which includes 
	deleting, updating, liking, commenting and replying to comments.
	"""

	form_class = CommentCreateForm
	form_class_reply = CommentReplyForm

	def setup(self, request, *args, **kwargs):
		self.post_instance = get_object_or_404(Post, pk=kwargs['post_id'], slug=kwargs['post_slug'])
		return super().setup(request, *args, **kwargs)

	def get(self, request, *args, **kwargs):
		comments = self.post_instance.pcomments.filter(is_reply=False)
		can_like = False
		if request.user.is_authenticated and self.post_instance.user_can_like(request.user):
			can_like = True
		return render(request, 'home/detail.html', {'post':self.post_instance, 'comments':comments,
					'form':self.form_class, 'form_reply':self.form_class_reply, 'can_like':can_like})

	@method_decorator(login_required)
	def post(self, request, *args, **kwargs):
		form = self.form_class(request.POST)
		if form.is_valid():
			new_comment = form.save(commit=False)
			new_comment.user = request.user
			new_comment.post = self.post_instance
			new_comment.save()
			messages.success(request, 'your comment submitted successfully', 'success')
			return redirect('home:post_detail', self.post_instance.id, self.post_instance.slug)




class PostDeleteView(LoginRequiredMixin, View):
	"""
	This view is about deleting posts, each user can only delete her 
	own post, except for the superuser who can also delete other users's posts.
	"""

	def get(self, request, post_id):
		post = get_object_or_404(Post ,pk=post_id)
		if post.user.id == request.user.id:
			post.delete()
			messages.success(request, 'Post deleted successfully.', 'success')
		elif request.user.is_superuser:
			post.delete()
			messages.success(request, 'Post deleted successfully.', 'success')
		else:
			messages.error(request, 'You cant delete this post...!', 'danger')
		return redirect('home:home')




class PostUpdateView(LoginRequiredMixin, View):
	"""This view is related to updating posts, 
	each user can only update his own post."""
		
	form_class = PostCreateUpdateForm

	def setup(self, request, *args, **kwargs):
		self.post_instance = get_object_or_404(Post ,pk=kwargs['post_id'])
		return super().setup(request, *args, **kwargs)

	def dispatch(self, request, *args, **kwargs):
		post = self.post_instance
		if post.user.id != request.user.id and not request.user.is_superuser:
			messages.error(request, 'You cant update this post...!', 'danger')
			return redirect('home:home')
		return super().dispatch(request, *args, **kwargs)

	def get(self, request, *args, **kwargs):
		post = self.post_instance
		form = self.form_class(instance=post)
		return render(request, 'home/update.html',{'form':form})
	
	def post(self, request, *args, **kwargs):
		post = self.post_instance
		form = self.form_class(request.POST, instance=post)
		if form.is_valid():
			new_post = form.save(commit=False)
			new_post.slug = slugify(form.cleaned_data['title'])
			new_post.user = request.user
			new_post.save()
			messages.success(request, 'You updated this post successfully.', 'success')
			return redirect('home:post_detail', post.id, post.slug)




class PostCreateView(LoginRequiredMixin, View):
	"""This view is for users to create posts."""

	form_class = PostCreateUpdateForm

	def get(self, request, *args, **kwargs):
		form = self.form_class
		return render(request, 'home/create.html', {'form':form})

	def post(self, request, *args, **kwargs):
		form = self.form_class(request.POST)
		if form.is_valid():
			new_post = form.save(commit=False)
			new_post.slug = slugify(form.cleaned_data['title'])
			new_post.user = request.user
			new_post.save()
			messages.success(request, 'You created a new post.', 'success')
			return redirect('home:post_detail', new_post.id, new_post.slug)
		


class PostAddReplyView(LoginRequiredMixin, View):
	"""
	This view is related to the response to the 
	comments of the users who commented on the posts.
	"""

	form_class = CommentReplyForm

	def post(self, request, post_id, comment_id):
		post = get_object_or_404(Post, id=post_id)
		comment = get_object_or_404(Comment, id=comment_id)
		form = self.form_class(request.POST)
		if form.is_valid():
			replies = form.save(commit=False)
			replies.user = request.user
			replies.post = post
			replies.reply = comment
			replies.is_reply = True
			replies.save()
			messages.success(request, 'Your reply submitted successfully', 'success')
			return redirect('home:post_detail', post.id, post.slug)
		

class PostLikeView(LoginRequiredMixin, View):
	"""This view is about liking posts by other users."""

	def get(self, request, post_id):
		post = get_object_or_404(Post, id=post_id)
		like = Vote.objects.filter(post=post, user=request.user)
		if like.exists():
			messages.error(request, 'You have already liked this post', 'danger')
		else:
			Vote.objects.create(post=post, user=request.user)
			messages.success(request, 'You liked this post', 'success')
		return redirect('home:post_detail', post.id, post.slug)
	


class PostSearchView(ListView):
	"""This view is related to searching and pagination."""

	paginate_by = 4
	template_name = "home/search_list.html"

	def get_queryset(self):
		search = self.request.GET.get('q')
		return Post.objects.filter(Q(title__icontains=search) | Q(body__icontains=search))
	
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['search'] = self.request.GET.get('q')
		return context

home/templates/home/create.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary" type="submit" value="Create">
    </form>
{% endblock %}

home/templates/home/detail.html
{% extends 'base.html' %}

{% block content %}
	<div style="font-family:'Shabnam'">
	<!--Delete and Update-->
		{% if request.user.id == post.user.id %}
			<a href="{% url 'home:post_delete' post.id %}" class="btn btn-danger">Delete</a>
			<a href="{% url 'home:post-update' post.id %}" class="btn btn-info">Update</a>

		{% elif request.user.is_superuser %}
			<a href="{% url 'home:post_delete' post.id %}" class="btn btn-danger">Delete</a>
			<a href="{% url 'home:post-update' post.id %}" class="btn btn-info">Update</a>

		{% endif %}

		<!--like Articles-->
		{% if request.user.is_authenticated %}
			<a class="{% if can_like %} disabled {% endif %} mb-1 mt-1 btn btn-primary" href="{% url 'home:post_like' post.id %}">Like {{ post.likes_count }}</a>
		{% endif %}
		<div class="card bg mt-3 b-3 p-3" style="background-color:#e5f6fb; line-height:35px; border:3px solid #7f8fa6">
			<p><a href="{% url 'account:user_profile' post.user.id %}">{{ post.user.username }}</a> - {{ post.updated|date:"Y-M" }}</p>
			<p>{{ post.body|safe }}</p>
		</div><br>

		<!--comments and Responses-->
			<p class="badge" style="background-color:purple">Put comment</p><br>
			{% if request.user.is_authenticated %}
				<form action="" method="post">
					{% csrf_token %}
					<details class="p-3 text" style="color:black">
						<summary>Comment</summary>
						{{ form.as_p }}
						<input class="btn btn-success" type="submit" value="Send">
					</details>
				</form>
			{% else %}
				<p class="alert alert-danger col-md-8">*Only logged in users can put comment!<p>
			{% endif %}<br>
			
			<p class="badge" style="background-color:darkblue">Number of comments: {{ comments.count }}</p><br>
		
			{% for comment in comments %}
				<div class="card bg-dark text-warning">
					<p class="card-header">{{ comment.user }} | {{ comment.created|timesince }}</p>
					<p class="card-body">{{ comment.body }}</p>
					
					{% if request.user.is_authenticated %}
						<form action="{% url 'home:add_reply' post.id comment.id %}" method="post">
							{% csrf_token %}
							<details class="p-3 text" style="color:white">
								<summary>Reply</summary>
								{{ form_reply.as_p }}
								<input class="btn btn-success" type="submit" value="Send">
							</details>
						</form>
					{% endif %}

					<!-- Reply -->
					{% with replies=comment.rcomments.all %}
						{% for reply in replies %}
							<p class="p-3 text-white bg" style="background-color:#00796B; margin-left:30px">{{ reply.user }} | {{ reply.created|timesince }}:<br/>{{ reply.body }}</p>
						{% endfor %}
					{% endwith %}
				</div>

			{% empty %}
				<p class="alert col-md-8" style="background-color:black; color:yellow">*You don't have any comments!<p>
			{% endfor %}
	</div>
{% endblock %}

home/templates/home/post_list.html
{% extends 'base.html' %}

{% block content %}
    <div style="font-family:'Shabnam'">
        <!-- Search -->
            <form class="form-inline" action="{% url 'home:post_search' %}">
                <input class="m-2" type="text" name="q" style="border-radius:10px" placeholder="Search">
                <button class="btn btn-success" style="padding:8px; border-radius:11px">Search</button>
            </form>

        <!-- Show posts in home page -->
            <div class="m-2 badge fs-6" style="background-color:blue">{% if request.user.is_authenticated %}Welcome {{user.username}}{% endif %}</div><br>
            <div class="row">
                {% for post in object_list %}
                    <div class="col-sm-13">
                    <div class="card bg m-2" style="background-color:#b2bec3">
                        <div class="card-body">
                            <h5 class="card-user">Author: {{ post.user}}</h5>
                            <h4 class="card-title">{{ post.title }}</h4>
                            <h6 class="card-title">{{ post.created|timesince }}</h6><br>
                            <p class="card-text">{{ post.body|safe|truncatewords:18 }}</p>
                            <a href="{{ post.get_absolute_url }}" class="btn btn-primary">Detail</a>
                        </div>
                    </div>
                    </div>
                {% empty %}
                    <p style="color:red; padding:6px">There aren't any post here...!</p>
                {% endfor %}
            </div><br>

        <!-- paginator -->
            {% if is_paginated %}
                <div class="clearfix pager-botton">
            {% if page_obj.has_previous %}
                <a class="btn btn-warning m-2 float-right" href="{% url 'home:home' page_obj.previous_page_number %}">New Posts &rarr;</a>
            {% endif %}
            {% if page_obj.has_next %}
                <a class="btn btn-warning m-2 float-right" href="{% url 'home:home' page_obj.next_page_number %}">Old Posts &larr;</a>
            {% endif %}
            </div>
        {% endif %}
    </div>
{% endblock %}

home/templates/home/search_list.html
{% extends 'home/post_list.html' %}

{% block previous_page_url %}
   {% url 'home:post_search' page_obj.previous_page_number %}?q={{search}}
{% endblock %}

{% block next_page_url %}
   {% url 'home:post_search' page_obj.next_page_number %}?q={{search}}
{% endblock %}

home/templates/home/update.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method='post' validate>
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-info" type="submit" value="Update">
    </form>
{% endblock %}