A/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('account/', include('account.urls', namespace='account')),
]

account/urls.py
from django.urls import path
from . import views


app_name = 'account'
urlpatterns = [
	path('register/', views.UserRegisterView.as_view(), name='user_register'),
	path('login/', views.UserLoginView.as_view(), name='user_login'),
	path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
	path('profile/<int:user_id>/', views.UserProfileView.as_view(), name='user_profile'),
    path('reset/', views.UserPasswordResetView.as_view(), name='reset_password'),
	path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
	path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
	path('confirm/complete', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('follow/<int:user_id>', views.UserFollowView.as_view(), name='user_follow'),
	path('unfollow/<int:user_id>', views.UserUnfollowView.as_view(), name='user_unfollow'),
    path('edit_user/', views.EditUserView.as_view(), name='edit_user'),
]

home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
	path('', views.HomeView.as_view(), name='home'),
    path('page/<int:page>', views.HomeView.as_view(), name="home"),
	path('post/<int:post_id>/<slug:post_slug>/', views.PostDetailView.as_view(), name='post_detail'),
	path('post/delete/<int:post_id>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('post/update/<int:post_id>/', views.PostUpdateView.as_view(), name='post-update'),
    path('post/create/', views.PostCreateView.as_view(), name='post_create'),
    path('reply/<int:post_id>/<int:comment_id>/', views.PostAddReplyView.as_view(), name="add_reply"),
    path('like/<int:post_id>/', views.PostLikeView.as_view(), name='post_like'),
    path('search/page/<int:page>/', views.PostSearchView.as_view(), name="post_search"),
    path('search/', views.PostSearchView.as_view(), name="post_search"),
]

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="navbar-nav">
      <a class="nav-link active" href="{% url 'home:home' %}">Home</a>
      {% if request.user.is_authenticated %}
      <a class="nav-link active" href="{% url 'home:post_create' %}">Create</a>
      <a class="nav-link active" href="{% url 'account:user_profile' request.user.id %}">Profile</a>
      <a class="nav-link active" href="{% url 'account:edit_user' %}">Edit Profile</a>
      <a class="nav-link active" href="{% url 'account:user_logout' %}">Logout</a>
      {% else %}
      <a class="nav-link active" href="{% url 'account:user_register' %}">Register</a>
      <a class="nav-link active" href="{% url 'account:reset_password' %}">Reset Password</a>
      <a class="nav-link active" href="{% url 'account:user_login' %}">Login</a>
      {% endif %}
    </div>
  </div>
</nav>